name: docker

on:
  push:
    paths:
      - 'server/package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t danigatunes/dudes-server server
      - name: Deploy
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u danigatunes --password-stdin && docker push danigatunes/dudes-server
